[build]
  # where your site’s static files live (adjust “.”, “public” or “dist” as needed)
  publish   = "."
  # where your Netlify Functions live
  functions = "functions"
  # 1 run your dummy root build
  # 2 then install the functions folder’s dependencies
  command   = "npm run build && npm install --prefix functions"


[dev]
  functions = "functions"  # for `netlify dev`
  port      = 8888
