[build]
  # your static site’s publish folder (e.g. "public", "dist", or "." if you have no build step)
  publish   = "public"    
  # point Netlify to your functions dir
  functions = "functions"

[dev]
  functions = "functions"  # for `netlify dev`
  port      = 8888
