[build]
  publish   = "public"              # or "." / your actual publish folder
  functions = "functions"
  # first install root deps (no-op), then install function deps 
  command   = "npm run build && npm install --prefix functions"

[dev]
  functions = "functions"  # for `netlify dev`
  port      = 8888
