# Docs for the Azure Web Apps Deploy action: https://github.com/azure/functions-action
# More GitHub Actions for Azure: https://github.com/Azure/actions

 name: Build and deploy Node.js project to Azure Function App - NPSBackend

 on:
   push:
     branches:
       - main
   workflow_dispatch:

 env:
-  AZURE_FUNCTIONAPP_PACKAGE_PATH: '.' # currently pointing at repo root
+  AZURE_FUNCTIONAPP_PACKAGE_PATH: '.nps-backend' # <-- change this to your Functions folder
   NODE_VERSION: '22.x'

 jobs:
   build:
     runs-on: windows-latest
     permissions:
       contents: read

     steps:
       - name: 'Checkout GitHub Action'
         uses: actions/checkout@v4

       - name: Setup Node ${{ env.NODE_VERSION }} Environment
         uses: actions/setup-node@v3
         with:
           node-version: ${{ env.NODE_VERSION }}

       - name: 'Resolve Project Dependencies Using Npm'
         shell: pwsh
         run: |
-          pushd './${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}'
+          pushd './.nps-backend'
           npm install
           npm run build --if-present
           npm run test --if-present
           popd

       - name: Upload artifact for deployment job
         uses: actions/upload-artifact@v4
         with:
           name: node-app
-          path: .
+          path: .  # still upload the entire repo; deploy action will pick .nps-backend

   deploy:
     runs-on: windows-latest
     needs: build
     permissions:
       id-token: write
       contents: read

     steps:
       - name: Download artifact from build job
         uses: actions/download-artifact@v4
         with:
           name: node-app

       - name: Login to Azure
         uses: azure/login@v2
         with:
           client-id:   ${{ secrets.AZUREAPPSERVICE_CLIENTID_… }}
           tenant-id:   ${{ secrets.AZUREAPPSERVICE_TENANTID_… }}
           subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_… }}

       - name: 'Run Azure Functions Action'
         uses: Azure/functions-action@v1
         id: fa
         with:
           app-name: 'NPSBackend'
           slot-name: 'Production'
-          package: ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}
+          package: '.nps-backend'   # <-- make sure this matches above
          
